main: commandbouncer.carlgo11.CommandBouncer.CommandBouncer
name: CommandBouncer
version: A0.1
author: Carlgo11, Cabbex
description: This plugin sends a command that's set in the config, when a user types a certain command.
commands:
  CommandBouncer:
    aliases: [cmdbnc, ccommandbouncer]
    description: Main command of CommandBouncer